# Generated by Django 5.2.4 on 2025-07-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('subtitle', models.TextField(verbose_name='Subtitle')),
            ],
            options={
                'verbose_name': 'Header Title',
                'verbose_name_plural': 'Header Titles',
            },
        ),
    ]
