# Generated by Django 5.2.4 on 2025-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(verbose_name='Main Text')),
                ('link_text', models.CharField(max_length=255, verbose_name='Link Text')),
                ('link_url', models.URLField(verbose_name='Link Url')),
            ],
        ),
    ]
