# Generated by Django 5.2.4 on 2025-07-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_2',
            field=models.ImageField(default=0, upload_to='gallery/', verbose_name='Image_2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default=0, max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
