# Generated by Django 5.2.4 on 2025-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gallery_image_2_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contacts Us',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
    ]
