# Generated by Django 5.2.4 on 2025-07-14 15:27

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountactUsWithPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=100, verbose_name='Chat')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Countact Us with phone',
                'verbose_name_plural': 'Countacts Us with phone',
            },
        ),
    ]
